# Build script: extract POKEMON素材 animated GIFs into frame strips + generate js/buddies.js
#
# Usage: powershell -File tools/build-sprites.ps1 [-Start 1] [-End 151] [-SkipNames]
# Output:
#   pet-app/sprites/anim/<dex>.png  - frame strip (frames laid horizontally)
#   pet-app/js/buddies.js           - catalog data (dex / zh-en names / frames / fps)

param(
  [int]$Start = 1,
  [int]$End = 151,
  [switch]$SkipNames
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"
Add-Type -AssemblyName System.Drawing

$src = (Get-ChildItem -Directory | Where-Object { $_.Name -like "POKEMON*素材" } | Select-Object -First 1).FullName
if (-not $src) { throw "POKEMON source folder not found" }
$animDir = "pet-app\sprites\anim"
New-Item -ItemType Directory -Force -Path $animDir | Out-Null

# --- 1. extract frames ---
$entries = @{}
$missing = @()
for ($n = $Start; $n -le $End; $n++) {
  $gifPath = Join-Path $src "$n.gif"
  if (-not (Test-Path $gifPath)) { $missing += $n; continue }
  $img = [System.Drawing.Image]::FromFile($gifPath)
  $dim = New-Object System.Drawing.Imaging.FrameDimension($img.FrameDimensionsList[0])
  $cnt = $img.GetFrameCount($dim)
  $w = $img.Width; $h = $img.Height

  $strip = New-Object System.Drawing.Bitmap(($w * $cnt), $h, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($strip)
  $g.Clear([System.Drawing.Color]::Transparent)

  # frame delays (centiseconds); default 10 if unavailable
  $delays = @()
  try {
    $pi = $img.GetPropertyItem(0x5100)
    for ($i = 0; $i -lt $cnt; $i++) { $delays += [Math]::Max([BitConverter]::ToInt32($pi.Value, $i * 4), 5) }
  } catch {
    for ($i = 0; $i -lt $cnt; $i++) { $delays += 10 }
  }

  for ($i = 0; $i -lt $cnt; $i++) {
    $img.SelectActiveFrame($dim, $i)
    $g.DrawImage($img, ($i * $w), 0, $w, $h)
  }
  $g.Dispose()
  $strip.Save((Join-Path $animDir "$n.png"), [System.Drawing.Imaging.ImageFormat]::Png)
  $strip.Dispose()
  $img.Dispose()

  $median = ($delays | Sort-Object)[[int]($delays.Count / 2)]
  $fps = [Math]::Round(100 / $median)
  if ($fps -lt 2) { $fps = 2 }
  if ($fps -gt 15) { $fps = 15 }
  $entries["$n"] = @{ dex = $n; frames = $cnt; fps = $fps; w = $w; h = $h }
  Write-Host "dex $n : ${w}x${h} x${cnt} frames, fps=$fps"
}
Write-Host "=== extracted $($entries.Count) / $Start..$End ==="
if ($missing.Count -gt 0) { Write-Host "MISSING: $($missing -join ',')" }

# --- 2. Chinese names + evolution from PokéAPI ---
$names = @{}
$evoFrom = @{}
if (-not $SkipNames) {
  foreach ($n in ($Start..$End)) {
    try {
      $spec = Invoke-RestMethod -Uri "https://pokeapi.co/api/v2/pokemon-species/$n" -TimeoutSec 20 -Headers @{ "User-Agent" = "pokemon-nfc-build" }
      $zh = $spec.names | Where-Object { $_.language.name -eq 'zh-Hans' } | Select-Object -First 1
      $en = $spec.names | Where-Object { $_.language.name -eq 'en' } | Select-Object -First 1
      $zhName = if ($zh) { $zh.name } else { $en.name }
      $names["$n"] = @{ zh = $zhName; en = $en.name }
      if ($spec.evolves_from_species -and $spec.evolves_from_species.url) {
        $m = [regex]::Match($spec.evolves_from_species.url, '/pokemon-species/(\d+)/')
        if ($m.Success) { $evoFrom["$n"] = [int]$m.Groups[1].Value }
      }
    } catch {
      $names["$n"] = @{ zh = "No.$n"; en = "No.$n" }
    }
    Start-Sleep -Milliseconds 120
  }
  Write-Host "=== names fetched: $($names.Count) ==="

  # 进化链：nextOf[x] = 1..151 中由 x 进化来的最小编号（范围内取最小的那个）
  $nextOf = @{}
  for ($j = $Start; $j -le $End; $j++) {
    if ($evoFrom.ContainsKey("$j")) {
      $from = $evoFrom["$j"]
      if ($from -ge $Start -and $from -le $End) {
        if (-not $nextOf.ContainsKey("$from") -or $j -lt $nextOf["$from"]) {
          $nextOf["$from"] = $j
        }
      }
    }
  }
}

# --- 3. generate js/buddies.js ---
if (-not $SkipNames) {
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine('/* auto-generated by tools/build-sprites.ps1 - do not edit */')
  [void]$sb.AppendLine('export const BUDDIES = {')
  foreach ($n in ($Start..$End)) {
    if (-not $entries["$n"]) { continue }
    $e = $entries["$n"]
    $nm = $names["$n"]
    $zhName = $nm.zh.Replace('"', '')
    $enName = $nm.en.Replace('"', '')
    $line = '  "' + $n + '": { dex: ' + $n + ', name: "' + $zhName + '", en: "' + $enName + '", frames: ' + $e.frames + ', fps: ' + $e.fps + ', w: ' + $e.w + ', h: ' + $e.h
    if ($nextOf.ContainsKey("$n")) { $line += ', next: ' + $nextOf["$n"] }
    $line += ' },'
    [void]$sb.AppendLine($line)
  }
  [void]$sb.AppendLine('};')
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('// dex number / Chinese name / English name all work')
  [void]$sb.AppendLine('const BY_NAME = {};')
  [void]$sb.AppendLine('for (const k of Object.keys(BUDDIES)) {')
  [void]$sb.AppendLine('  const b = BUDDIES[k];')
  [void]$sb.AppendLine('  BY_NAME[b.name.toLowerCase()] = b.dex;')
  [void]$sb.AppendLine('  if (b.en) BY_NAME[b.en.toLowerCase()] = b.dex;')
  [void]$sb.AppendLine('}')
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('export function findBuddy(id) {')
  [void]$sb.AppendLine('  if (id == null) return null;')
  [void]$sb.AppendLine('  const key = String(id).trim().toLowerCase();')
  [void]$sb.AppendLine('  if (BUDDIES[key]) return BUDDIES[key];')
  [void]$sb.AppendLine('  const dex = BY_NAME[key];')
  [void]$sb.AppendLine('  return dex ? BUDDIES[String(dex)] : null;')
  [void]$sb.AppendLine('}')
  $utf8 = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText((Join-Path (Get-Location) "pet-app\js\buddies.js"), $sb.ToString(), $utf8)
  Write-Host "=== buddies.js written ==="
}

# --- 4. size report ---
$total = (Get-ChildItem $animDir -File | Measure-Object -Property Length -Sum).Sum
Write-Host "=== anim folder total: $([math]::Round($total/1MB, 2)) MB, files: $((Get-ChildItem $animDir -File).Count) ==="
